version: '3'
name: villa-babes-buff-docker

services:

  # redis:
  #   image: redis:6-alpine
  #   container_name: 'redis'
  #   restart: always
  #   ports:
  #     - 127.0.0.1:6379:6379
  #   command: redis-server --save 20 1 --loglevel warning --requirepass v0RedisSecret
  #   volumes: 
  #     - redis:/data

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresUserVB
      POSTGRES_PASSWORD: pgSuperSecretMnogaBycaBab
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@villababes.com
  #     PGADMIN_DEFAULT_PASSWORD: pgAdminSuperPuperSecret
  #   ports:
  #     - "5050:80"

networks:
  mongo-compose-network:
    driver: bridge
 
volumes:
  redis:
    driver: local
  mongo:
    driver: local
