name: redeploy prod

on:
  push:
    branches: [ prod ]

jobs:
  redeploy-prod-base:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: redeploy prod on test server
        env:
            PRIVATE_KEY:  ${{ secrets.PROD_PRIVATE_KEY  }}
            HOSTNAME :    ${{ secrets.PROD_SSH_HOST  }}
            USER_NAME :   ${{ secrets.PROD_SSH_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && 
          chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=off -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ~symmetrical-waffle &&
            git fetch --all &&
            git checkout prod &&
            git reset --hard origin/prod &&
            git pull origin prod &&
            bash init/init.bash
          '
